package com.example.qnuquiz.entity;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

// Generated Nov 25, 2025, 4:34:35 PM by Hibernate Tools 7.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "departments", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Departments implements java.io.Serializable {

    private long id;
    private String name;
    private String description;
    private Timestamp createdAt;
    private Set<Teachers> teacherses = new HashSet<Teachers>(0);
    private Set<Announcements> announcementses = new HashSet<Announcements>(0);
    private Set<Students> studentses = new HashSet<Students>(0);
    private Set<Classes> classeses = new HashSet<Classes>(0);

    public Departments() {
    }

    public Departments(long id, String name, Timestamp createdAt) {
        this.id = id;
        this.name = name;
        this.createdAt = createdAt;
    }

    public Departments(long id, String name, String description, Timestamp createdAt, Set<Teachers> teacherses,
            Set<Announcements> announcementses, Set<Students> studentses, Set<Classes> classeses) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.createdAt = createdAt;
        this.teacherses = teacherses;
        this.announcementses = announcementses;
        this.studentses = studentses;
        this.classeses = classeses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false, length = 256)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set<Teachers> getTeacherses() {
        return this.teacherses;
    }

    public void setTeacherses(Set<Teachers> teacherses) {
        this.teacherses = teacherses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set<Announcements> getAnnouncementses() {
        return this.announcementses;
    }

    public void setAnnouncementses(Set<Announcements> announcementses) {
        this.announcementses = announcementses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set<Students> getStudentses() {
        return this.studentses;
    }

    public void setStudentses(Set<Students> studentses) {
        this.studentses = studentses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set<Classes> getClasseses() {
        return this.classeses;
    }

    public void setClasseses(Set<Classes> classeses) {
        this.classeses = classeses;
    }

}
