package com.example.qnuquiz.entity;
// Generated Oct 12, 2025, 7:49:47 PM by Hibernate Tools 7.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ExamQuestionsId generated by hbm2java
 */
@Embeddable
public class ExamQuestionsId implements java.io.Serializable {

    private long examId;
    private long questionId;

    public ExamQuestionsId() {
    }

    public ExamQuestionsId(long examId, long questionId) {
        this.examId = examId;
        this.questionId = questionId;
    }

    @Column(name = "exam_id", nullable = false)
    public long getExamId() {
        return this.examId;
    }

    public void setExamId(long examId) {
        this.examId = examId;
    }

    @Column(name = "question_id", nullable = false)
    public long getQuestionId() {
        return this.questionId;
    }

    public void setQuestionId(long questionId) {
        this.questionId = questionId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ExamQuestionsId))
            return false;
        ExamQuestionsId castOther = (ExamQuestionsId) other;

        return (this.getExamId() == castOther.getExamId())
                && (this.getQuestionId() == castOther.getQuestionId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getExamId();
        result = 37 * result + (int) this.getQuestionId();
        return result;
    }

}
