package com.example.qnuquiz.entity;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import com.example.qnuquiz.dto.analytics.ClassPerformanceDto;
import com.example.qnuquiz.dto.analytics.ExamAnalyticsDto;
import com.example.qnuquiz.dto.analytics.QuestionAnalyticsDto;
import com.example.qnuquiz.dto.analytics.ScoreDistributionDto;
import com.example.qnuquiz.dto.analytics.StudentAttemptDto;

// Generated Nov 25, 2025, 4:34:35 PM by Hibernate Tools 7.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.ColumnResult;
import jakarta.persistence.ConstructorResult;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SqlResultSetMapping;
import jakarta.persistence.SqlResultSetMappings;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * ExamAttempts generated by hbm2java
 */
@Entity
@Table(name = "exam_attempts")
@SqlResultSetMappings({
        @SqlResultSetMapping(name = "StudentAttemptDtoMapping", classes = @ConstructorResult(targetClass = StudentAttemptDto.class, columns = {
                @ColumnResult(name = "student_code", type = String.class),
                @ColumnResult(name = "full_name", type = String.class),
                @ColumnResult(name = "class_name", type = String.class),
                @ColumnResult(name = "start_time", type = LocalDateTime.class),
                @ColumnResult(name = "end_time", type = LocalDateTime.class),
                @ColumnResult(name = "duration_minutes", type = Double.class),
                @ColumnResult(name = "score", type = Double.class),
                @ColumnResult(name = "submitted", type = Boolean.class)
        })),
        @SqlResultSetMapping(name = "ExamAnalyticsDtoMapping", classes = @ConstructorResult(targetClass = ExamAnalyticsDto.class, columns = {
                @ColumnResult(name = "exam_id", type = Long.class),
                @ColumnResult(name = "exam_title", type = String.class),
                @ColumnResult(name = "total_attempts", type = Long.class),
                @ColumnResult(name = "total_submitted", type = Long.class),
                @ColumnResult(name = "avg_score", type = Double.class),
                @ColumnResult(name = "max_score", type = Double.class),
                @ColumnResult(name = "min_score", type = Double.class)
        })),
        @SqlResultSetMapping(name = "ClassPerformanceDtoMapping", classes = @ConstructorResult(targetClass = ClassPerformanceDto.class, columns = {
                @ColumnResult(name = "class_name", type = String.class),
                @ColumnResult(name = "student_count", type = Long.class),
                @ColumnResult(name = "avg_score_per_class", type = Double.class)
        })),
        @SqlResultSetMapping(name = "ScoreDistributionDtoMapping", classes = @ConstructorResult(targetClass = ScoreDistributionDto.class, columns = {
                @ColumnResult(name = "title", type = String.class),
                @ColumnResult(name = "excellent_count", type = Long.class),
                @ColumnResult(name = "good_count", type = Long.class),
                @ColumnResult(name = "average_count", type = Long.class),
                @ColumnResult(name = "fail_count", type = Long.class)
        })),
        @SqlResultSetMapping(name = "QuestionAnalyticsDtoMapping", classes = @ConstructorResult(targetClass = QuestionAnalyticsDto.class, columns = {
                @ColumnResult(name = "question_content", type = String.class),
                @ColumnResult(name = "total_answers", type = Long.class),
                @ColumnResult(name = "correct_count", type = Long.class),
                @ColumnResult(name = "wrong_count", type = Long.class),
                @ColumnResult(name = "correct_rate", type = Double.class)
        }))
})
public class ExamAttempts implements java.io.Serializable {

    private long id;
    private Students students;
    private Exams exams;
    private Timestamp startTime;
    private Timestamp endTime;
    private Integer score;
    private boolean submitted;
    private Timestamp createdAt;
    private Set<ExamAnswers> examAnswerses = new HashSet<ExamAnswers>(0);

    public ExamAttempts() {
    }

    public ExamAttempts(long id, Timestamp startTime, boolean submitted, Timestamp createdAt) {
        this.id = id;
        this.startTime = startTime;
        this.submitted = submitted;
        this.createdAt = createdAt;
    }

    public ExamAttempts(long id, Students students, Exams exams, Timestamp startTime, Timestamp endTime, Integer score,
            boolean submitted, Timestamp createdAt, Set<ExamAnswers> examAnswerses) {
        this.id = id;
        this.students = students;
        this.exams = exams;
        this.startTime = startTime;
        this.endTime = endTime;
        this.score = score;
        this.submitted = submitted;
        this.createdAt = createdAt;
        this.examAnswerses = examAnswerses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    public Students getStudents() {
        return this.students;
    }

    public void setStudents(Students students) {
        this.students = students;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exam_id")
    public Exams getExams() {
        return this.exams;
    }

    public void setExams(Exams exams) {
        this.exams = exams;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false, length = 35)
    public Timestamp getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 35)
    public Timestamp getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    @Column(name = "score")
    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    @Column(name = "submitted", nullable = false)
    public boolean isSubmitted() {
        return this.submitted;
    }

    public void setSubmitted(boolean submitted) {
        this.submitted = submitted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "examAttempts")
    public Set<ExamAnswers> getExamAnswerses() {
        return this.examAnswerses;
    }

    public void setExamAnswerses(Set<ExamAnswers> examAnswerses) {
        this.examAnswerses = examAnswerses;
    }

}