package com.example.qnuquiz.entity;
// Generated Oct 12, 2025, 7:49:47 PM by Hibernate Tools 7.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Leaderboard generated by hbm2java
 */
@Entity
@Table(name = "leaderboard", schema = "public", catalog = "defaultdb")
public class Leaderboard implements java.io.Serializable {

    private long id;
    private Students students;
    private Exams exams;
    private BigDecimal score;
    private Integer rank;
    private Timestamp generatedAt;

    public Leaderboard() {
    }

    public Leaderboard(long id, Timestamp generatedAt) {
        this.id = id;
        this.generatedAt = generatedAt;
    }

    public Leaderboard(long id, Students students, Exams exams, BigDecimal score, Integer rank, Timestamp generatedAt) {
        this.id = id;
        this.students = students;
        this.exams = exams;
        this.score = score;
        this.rank = rank;
        this.generatedAt = generatedAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    public Students getStudents() {
        return this.students;
    }

    public void setStudents(Students students) {
        this.students = students;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exam_id")
    public Exams getExams() {
        return this.exams;
    }

    public void setExams(Exams exams) {
        this.exams = exams;
    }

    @Column(name = "score", precision = 8, scale = 3)
    public BigDecimal getScore() {
        return this.score;
    }

    public void setScore(BigDecimal score) {
        this.score = score;
    }

    @Column(name = "rank")
    public Integer getRank() {
        return this.rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "generated_at", nullable = false, length = 35)
    public Timestamp getGeneratedAt() {
        return this.generatedAt;
    }

    public void setGeneratedAt(Timestamp generatedAt) {
        this.generatedAt = generatedAt;
    }

}
