package com.example.qnuquiz.entity;

// default package

// Generated Nov 4, 2025, 9:33:18 PM by Hibernate Tools 7.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions", schema = "public", catalog = "defaultdb")
public class Questions implements java.io.Serializable {

    private long id;
    private QuestionCategories questionCategories;
    private Exams exams;
    private Users users;
    private String content;
    private String type;
    private BigDecimal points;
    private Integer ordering;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private Set<ExamAnswers> examAnswerses = new HashSet<ExamAnswers>(0);
    private Set<QuestionOptions> questionOptionses = new HashSet<QuestionOptions>(0);
    private Set<Feedbacks> feedbackses = new HashSet<Feedbacks>(0);

    public Questions() {
    }

    public Questions(long id, Exams exams, String content, String type, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.exams = exams;
        this.content = content;
        this.type = type;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Questions(long id, QuestionCategories questionCategories, Exams exams, Users users, String content,
            String type, BigDecimal points, Integer ordering, Timestamp createdAt, Timestamp updatedAt,
            Set<ExamAnswers> examAnswerses, Set<QuestionOptions> questionOptionses, Set<Feedbacks> feedbackses) {
        this.id = id;
        this.questionCategories = questionCategories;
        this.exams = exams;
        this.users = users;
        this.content = content;
        this.type = type;
        this.points = points;
        this.ordering = ordering;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.examAnswerses = examAnswerses;
        this.questionOptionses = questionOptionses;
        this.feedbackses = feedbackses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    public QuestionCategories getQuestionCategories() {
        return this.questionCategories;
    }

    public void setQuestionCategories(QuestionCategories questionCategories) {
        this.questionCategories = questionCategories;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exam_id", nullable = false)
    public Exams getExams() {
        return this.exams;
    }

    public void setExams(Exams exams) {
        this.exams = exams;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "content", nullable = false)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "type", nullable = false)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "points", precision = 6, scale = 2)
    public BigDecimal getPoints() {
        return this.points;
    }

    public void setPoints(BigDecimal points) {
        this.points = points;
    }

    @Column(name = "ordering")
    public Integer getOrdering() {
        return this.ordering;
    }

    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
    public Set<ExamAnswers> getExamAnswerses() {
        return this.examAnswerses;
    }

    public void setExamAnswerses(Set<ExamAnswers> examAnswerses) {
        this.examAnswerses = examAnswerses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
    public Set<QuestionOptions> getQuestionOptionses() {
        return this.questionOptionses;
    }

    public void setQuestionOptionses(Set<QuestionOptions> questionOptionses) {
        this.questionOptionses = questionOptionses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
    public Set<Feedbacks> getFeedbackses() {
        return this.feedbackses;
    }

    public void setFeedbackses(Set<Feedbacks> feedbackses) {
        this.feedbackses = feedbackses;
    }

}
