package com.example.qnuquiz.entity;
// Generated Oct 12, 2025, 7:49:47 PM by Hibernate Tools 7.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "students", schema = "public", catalog = "defaultdb", uniqueConstraints = {
        @UniqueConstraint(columnNames = "student_code"), @UniqueConstraint(columnNames = "user_id") })
public class Students implements java.io.Serializable {

    private long id;
    private Classes classes;
    private Users users;
    private Departments departments;
    private String studentCode;
    private BigDecimal gpa;
    private Timestamp createdAt;
    private Set<Leaderboard> leaderboards = new HashSet<Leaderboard>(0);
    private Set<ExamAttempts> examAttemptses = new HashSet<ExamAttempts>(0);

    public Students() {
    }

    public Students(long id, Users users, String studentCode, Timestamp createdAt) {
        this.id = id;
        this.users = users;
        this.studentCode = studentCode;
        this.createdAt = createdAt;
    }

    public Students(long id, Classes classes, Users users, Departments departments, String studentCode, BigDecimal gpa,
            Timestamp createdAt, Set<Leaderboard> leaderboards, Set<ExamAttempts> examAttemptses) {
        this.id = id;
        this.classes = classes;
        this.users = users;
        this.departments = departments;
        this.studentCode = studentCode;
        this.gpa = gpa;
        this.createdAt = createdAt;
        this.leaderboards = leaderboards;
        this.examAttemptses = examAttemptses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "class_id")
    public Classes getClasses() {
        return this.classes;
    }

    public void setClasses(Classes classes) {
        this.classes = classes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", unique = true, nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
    public Departments getDepartments() {
        return this.departments;
    }

    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    @Column(name = "student_code", unique = true, nullable = false, length = 64)
    public String getStudentCode() {
        return this.studentCode;
    }

    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    @Column(name = "gpa", precision = 3, scale = 2)
    public BigDecimal getGpa() {
        return this.gpa;
    }

    public void setGpa(BigDecimal gpa) {
        this.gpa = gpa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
    public Set<Leaderboard> getLeaderboards() {
        return this.leaderboards;
    }

    public void setLeaderboards(Set<Leaderboard> leaderboards) {
        this.leaderboards = leaderboards;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
    public Set<ExamAttempts> getExamAttemptses() {
        return this.examAttemptses;
    }

    public void setExamAttemptses(Set<ExamAttempts> examAttemptses) {
        this.examAttemptses = examAttemptses;
    }

}
